### ISSUE TITLE
Create use case diagram (function for slackbot to send warnings, all use cases diagram)

### ISSUE THREAD

**Issue by murakami10** [satokibi44/Tweet_Analyzing#1]
Usecase分析を行った結果をUsecase図にまとめる
Create use case diagram

**Comment by murakami10** [comment]
Add all diagram and fix usecase.
https://github.com/satokibi44/Tweet_Analyzing/commit/1211c988b1b7e1452010d521507119aeb3802dc1

Add usecase diagram of function for slackbot to send warnings.
https://github.com/satokibi44/Tweet_Analyzing/commit/30bcbf90cc7cf4b1aff7ad348fcfe3e2a7991115

**Comment by KKKKKXY** [comment]
This issue will include all use cases diagram and the use case diagram of "function for slackbot to send warnings".
