### ISSUE TITLE
Design the infrastructure.

### ISSUE THREAD

**Issue by satokibi44** [satokibi44/Tweet_Analyzing#25]

**Comment by murakami10** [comment]
定期実行をlambda + Cloud watchで行って、定期的にslackのメッセージを取得する

https://qiita.com/hujuu/items/f73468e13b2c7be8f2cc

**Comment by satokibi44** [comment]
In english: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/RunLambdaSchedule.html
