### ISSUE TITLE
remake slander api infrastructure

### ISSUE THREAD

**Issue by satokibi44** [satokibi44/Tweet_Analyzing#31]
complete drawing
![image](https://user-images.githubusercontent.com/52820882/151495370-fac780e2-9af6-4ff9-9e52-6e0d2e268b86.png)

**Comment by satokibi44** [comment]
The Slander API is now up and running.
Please try it out.
This is example
http://3.143.237.69/kusorep/score/?msg="お前馬鹿かよ"
Memory out error may occur.

**Comment by KKKKKXY** [comment]
Hi Sato-san, I found a problem with this api:
If I send the sentence is "**"お前馬鹿かよ"**" (sentence with A pair of double quotes), the kusoripu_score = 0.670905590057373
But if I send the sentence is **"お前馬鹿かよ"** (no double quotes), the kusoripu_score = 0.9252830743789673


Like this:
<img width="440" alt="Screen Shot 2022-02-10 at 03 09 11" src="https://user-images.githubusercontent.com/44742053/153272621-27126887-327a-4858-8718-5342cd6601ff.png">
